[package]
name = "day-19"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom.workspace = true

[dev-dependencies]
indoc.workspace = true
