[workspace]
resolver = "2"
members = [
    "day-01",
    "day-02",
    "day-03",
    "day-05",
    "day-06",
    "day-07"
]

[workspace.dependencies]
indoc = "2.0.4"
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"
