[package]
name = "day-20"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom.workspace = true
num = "0.4.1"

[dev-dependencies]
indoc.workspace = true
